config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get    '/about',   to: 'homepage#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  get 'sessions/new'
  
  get 'homepage/index'
  resources :exercises

  resources :aboutus

  resources :nutritions
  root 'homepage#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
end

app/models/nutrition.rb
class Nutrition < ActiveRecord::Base
    def calories
        (((10 * ((45/100) * self.weight.to_i)) + (6.25 * (2.54 * self.height.to_i))) - (5* self.age.to_i)) +5
    end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
    
    def exercise_params
        params.require(:exercise).permit(:muscle, :description)
    end
    
    def index
        @exercises = Exercise.all
    end
    def show
        @exercise = Exercise.find params[:id] #look up exercise by unique muscle id
    end
    def new
        @exercise = Exercise.new
    end
    def create
        @exercise = Exercise.create!(exercise_params)
        flash[:notice] = "#{@exercise.muscle} was successfully created."
        redirect_to exercises_path
    end
    
    def destroy
        @exercise = Exercise.find params[:id]
        @exercise.destroy
        flash[:notice] = "Exercise '#{@exercise.muscle}' deleted."
        redirect_to exercises_path
    end
    def edit
        @exercise = Exercise.find params[:id]
    end
    
    def update
        @exercise = Exercise.find params[:id]
        @exercise.update_attributes!(exercise_params)
        flash[:notice] = "#{@exercise.muscle} was successfully updated."
        redirect_to exercise_path(@exercise)
           # redirect_to :action => 'show', :id => @exercise.id

    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def index
    end
end

app/controllers/nutritions_controller.rb
class NutritionsController < ApplicationController
    def nutrition_params
        params.require(:nutrition).permit(:height,:weight, :age)
    end
    def index
        @nutritions = Nutrition.all
    end

    def new
        @nutrition = Nutrition.new
    end
    def show
        @nutrition = Nutrition.find params[:id]
    end
    def create
        @nutrition = Nutrition.create!(nutrition_params)
        if @nutrition.save
            redirect_to nutritions_path, notice: "Nutrition was successfully created"
        end
       # flash[:notice] = "#{@nutrition.height} was successfully created."
        #redirect_to nutritions_path
    end
    def update 
        @nutrition = Nutrition.find params[:id]
        @nutrition.update_attributes!(nutrition_params)
        flash[:notice] = "#{@nutrition.height} was successfully updated."
        redirect_to nutrition_path(@nutrition)
    end
    def edit
        @nutrition = Nutrition.find params[:id]
    end
    def destroy
        @nutrition = Nutrition.find params[:id]
        @nutrition.destroy
        flash[:notice] = "Nutrition '#{@nutrition.height}' deleted."
        redirect_to nutritions_path
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to user
    else
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:success] = "Welcome to HealthyU!"
            redirect_to @user
        else
            render 'new'
        end
    end
    private
        def user_params
            params.require(:user).permit(:name, :email, :password)
        end
    def destroy
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, size: 80)
    end
end

app/views/aboutus/index.html.haml
%h1{id: "heading"}About Us

%center
%table{:border => 0, id: "team"}
    %tbody
        %tr
            %th The Team
        %tr
            %td Mukul Batra
        %tr
            %td Steven Liounis
        %tr
            %td Renee Russo
        %tr
            %td Piruthviraj Angamuthu Selvaraju
        %tr
            %td Mei Sheinbaum

app/views/exercises/edit.html.haml
%h1 Edit Existing Muscle

= form_tag exercise_path(@exercise), :method => :put do

  = label :exercise, :muscle, 'Muscle'
  = text_field :exercise, 'muscle'

  = label :exercise, :description, 'Description'
  = text_field :exercise, 'description'

  = submit_tag 'Update Muscle Info'
  

app/views/exercises/new.html.haml
%center

  %h1 Enter New Muscle Exercise

  = form_tag exercises_path do

    = label :exercise, :muscle, 'Muscle'
    = text_field :exercise, 'muscle'

    = label :exercise, :description, 'Description'
    = text_field :exercise, 'description'

    = submit_tag 'Save Exercise'
    
%br
%br
%br
%br

app/views/exercises/show.html.haml
%h2 Details about your #{@exercise.muscle} muscle exercise

%ul#details
  %li
    Muscle Name:
    = @exercise.muscle
  %li
    Muscle Exercise:
    = @exercise.description

= link_to '<button type="button">Edit</button>'.html_safe, edit_exercise_path(@exercise)
= button_to 'Delete', exercise_path(@exercise), :method => :delete, :confirm => 'Are you sure?'
= link_to '<button type="button">Back</button>'.html_safe, exercises_path

app/views/homepage/index.html.haml
%h1{id: "heading"} HealthyU

%center
    %h2 Looking to lose weight? Or looking to get brawn and big? What would be more convenient other than knowing what muscle to work out and what food to eat? We're going to help you keep a record of your workout logs and the caloric intake as well as the macros you'll need to achieve your goal.

%br
%center
    = image_tag("homepage.jpg", :alt => "HealthyU") 

%br
%center
    = link_to '<button type="button">Login</button>'.html_safe, sessions_new_path

%br
%br
    = link_to "All Users", users_path 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthyU</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>




<%= yield %>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li><%= link_to "My Exercises", exercises_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<br>
<br>
<table>
  <tr>
    <td>
      <%= link_to "Home", '/', {id: "newexer"} %>
    </td>
    <td>
      <%= link_to "About Us", '/aboutus', {id: "newexer"} %>
    </td>
    <td>
      <%= link_to 'Users', users_path, {id: "links"} %>
    </td>
    <td>
      <%= link_to "Exercises Page", exercises_path, {id: "newexer"} %>
    </td>
    <td>
      <%= link_to "Nutritions Page", 'nutritions', {id: "newexer"} %>
    </td>
    <td>
      <%= link_to "Contact Us", '', {id: "newexer"} %>
    </td>
  </tr>
</table>
</body>
</html>

app/views/nutrition/index.html.haml
%h1{id: "heading"} Nutrition 

Description

%hr 

%br
%br
%table{:border => 1, id: "nutri"}
    %tbody
        %tr
            %th Group 1
            %th Group 2
            %th Group 3
        %tr
            %td Foods in Group 1
            %td Foods in Group 2
            %td Foods in Group 3
%br

%center
    Calorie Intake Calculator
    %br

%table{:border => 1, id: "calculator"}
    %tbody
        %tr
            %th Height
            %th Weight
            %th Age
        %tr
            %td
                %input#height{:name => "height", :size => "10", :type => "text"}/
                
            %td
                %input#weight{:name => "weight", :size => "10", :type => "text"}/
            %td
                %input#age{:name => "age", :size => "10", :type => "text"}/
%br
%center
    Something that sends input data to params
    %br
    Calculator Output: 
    %output= @Calc
%br

%table
    %tr
        %td= link_to "Home", '/', {id: "newexer"}
        %td= link_to "About Us", '', {id: "newexer"}
        %td= link_to "Exercises", '/exercises', {id: "newexer"}
        %td= link_to "Nutrition", 'nutrition', {id: "newexer"}
        %td= link_to "Contact Us", '', {id: "newexer"}

app/views/nutritions/edit.html.haml
%h1 Edit Nutrition Information

= form_tag nutrition_path(@nutrition), :method => :put do

  = label :nutrition, :height, 'height (inches)'
  = text_field :nutrition, 'height'

  = label :nutrition, :weight, 'weight (pounds)'
  = text_field :nutrition, 'weight'

  = label :nutrition, :age, 'age (years)'
  = text_field :nutrition, 'age'  

  = submit_tag 'Update Nutrition Information'

app/views/nutritions/index.html.haml
%center
    = image_tag("nutrition.jpg", :alt => "HealthyU") 

%center
    This is a nutrition page to provide you with heathy eating habits
    %br
%hr 

%br
%br

%table{:border => 1, id: "nutri"}
    %tr
        %th Protein
        %th Carbohydrates
        %th Fats
    %tr
        %td 
            
            %ul 
            
            %li Greek Yogurt
            Protein Power: 23 g per 8 oz. serving
            
            %li Cottage Cheese
            Protein Power: 14 g per 0.5 cup serving
            %li Eggs
            Protein Power: 6 g per 1 large egg
            
            %li Peanut Butter
            Protein Power: 8 g per 2 tbsp serving
            
            %li Percent Milk
            Protein Power: 8 g per 1 cup serving
            
            %li Smoothies
            Protein Power: 16 g per 1 cup serving
            
            %li Steak (Top Or Bottom Round)
            Protein Power: 23 g per 3 oz. serving
            
            %li Ground Beef (90% Lean)
            Protein Power: 18 g per 3 oz. serving
            
            %li Pork Chops (Boneless)
            Protein Power: 26 g per 3 oz. serving
            
            %li Chicken Breast (Boneless And Skinless)
            Protein Power: 24 g per 3 oz. serving
            
            %li Turkey Breast
            Protein Power: 24 g per 3 oz. serving
            
            %li Yellowfin Tuna
            Protein Power: 25 g per 3 oz. serving
            
            %li Pepperoni
            Protein Power: 18 g per 3 oz. serving
            
            
        %td 
            %ul
            
            %li grains like rice, oatmeal, and barley
            %li grain-based foods like bread, cereal, pasta, and crackers
            %li starchy vegetables like potatoes, peas and corn
            %li fruit and juice
            %li milk and yogurt
            %li dried beans like pinto beans and soy products like veggie burgers
            %li sweets and snack foods like sodas, juice drinks, cake, cookies, candy, and chips
            %li Non-starchy vegetables like lettuce, cucumbers, broccoli, and cauliflower have very little carbohydrate and minimal impact on your blood glucose.

        %td 
            %ul
            %li avocado 
            %li butter 
            %li cheese
            %li olive oil 
            %li fish, nuts 
            %li coconut 
            %li chia seeds
%br
%br
%center
    Input Information to get a healthy caloric intake to lose two pounds per week
    %br
%br
%center
    = link_to '<button type="button">Add New Info</button>'.html_safe, new_nutrition_path
    %br
%br
%table{:border => 1}
    %tbody
        %tr
            %td= "Height"
            %td= "Weight"
            %td= "Age"
            %td= "Caloric Intake"
    - @nutritions.each do |nutrition|
        %tr
            %td= link_to(nutrition.height, {:action => 'show', :id => nutrition.id}, :class => 'action show')
            %td= nutrition.weight
            %td= nutrition.age
            %td= nutrition.calories
%br
%br

app/views/nutritions/new.html.haml
%h1 Enter New Nutrition Information

= form_tag nutritions_path do

  = label :nutrition, :height, 'height (inches)'
  = text_field :nutrition, 'height'

  = label :nutrition, :weight, 'weight (pounds)'
  = text_field :nutrition, 'weight'

  = label :nutrition, :age, 'age (years)'
  = text_field :nutrition, 'age'
  

  = submit_tag 'Save Information'

app/views/nutritions/show.html.haml
%h2 Details about your suggested #{@nutrition.calories} caloric intake

%ul#details
  %li
    Height:
    = @nutrition.height
  %li
    Weight:
    = @nutrition.weight
  %li
    Age:
    = @nutrition.age
  %li
    Calories:
    = @nutrition.calories

= link_to '<button type="button">Edit</button>'.html_safe, edit_nutrition_path(@nutrition)
= button_to 'Delete', nutrition_path(@nutrition), :method => :delete, :confirm => 'Are you sure?'
= link_to '<button type="button">Back</button>'.html_safe, nutritions_path

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>
<li><%= link_to "Profile", current_user %></li>
<li></li><%= link_to "Log out", logout_path, method: :delete %></li>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>